# -*- coding: utf-8 -*-
"""PythonBasics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OjX4Lk4UdNx4gJwDdfRzKgviFu9sJrdu
"""

print("Hello World");

a=float(input("enter first number"))
b=float(input("enter second number"))

print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**b)
print(a//b)
print(a%b)

#comparision operators
a=20
b=30
c=20
print(a==b)
print(a==c)
print(a>c)
print(c<=a)
print(a<=b)
print(b>=c)
print(a is not c)

a=30
b=4
a+=b
print(a)
a-=b
print(a)
a*=b
print(a)

#Logical operators
a=30
b=20
print(a==b or a>b)
print(a<b and a==b)
print(not(a!=b))

#identity operators
a=20
b=30
c=20
print(a is c)
print(b is c)
print(a is not c)

#Membership operators
lst=[1,2,3,"hello"]
print(1 in lst)
print(5 not in lst)
print("hello" not in lst)

n=5
fact=1
while(n!=0):
  fact=fact*n
  n=n-1
print(fact)

#lists
# a list is a heterogenous datatype
lst=[1,2,3,4,4.5,True,"hello"]
print(lst)

#conditional statements
#simple if and elif
a=20
b=20
if a>b:
  print(a)
elif a<b:
  print(b)
else:
  print("equal")

#and and or operators in conditions
a=30
b=40
c=30
if not a>c:
  print(c)
if b>a or c>b:
  print(a)
if a>b and a>c:
  print(a)
if b>a and b>c:
  print(b)
if c>a and c>b:
  print(c)

a=30
b=40
c=30
if  not a>c:
  print(c)
  if b>a or c>b:
    print(a)
    if a>b and a>c:
      print(a)

n=int(input("enter the range"))
oddlst=[]
evenlst=[]
for i in range(1,n+1):
  if i % 2 ==0:
    evenlst.append(i)
  else:
    oddlst.append(i)
print(evenlst)
print(oddlst)

n=int(9)
for i in range(1,n+1):
  print(i)

# list operations
lst=[]
lst.append(10)
print(lst)
lst.append(20)
print(lst)
lst.append(5)
print(lst)
lst.sort()
print(lst)
lst.remove(10)
print(lst)
lst.append(15)
print(lst)
lst
lst.pop()
print(lst)
lst
lst.insert(2,30)
print(lst)
lst.reverse()
print(lst)
lst.append(20)
print(lst)
lst.count(20)

lst+lst

lst*2

lst.index(20)

min(lst)

max(lst)